version: '3.4'
services:
  mysql:
    image: mysql/mysql-server:latest
    container_name: apiDatabase
    ports:
     - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=root_pa55w0rd
      - MYSQL_DATABASE=apiDatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pa55w0rd
    volumes:
     - ./db/dump:/docker-entrypoint-initdb.d
  api:
    links:
      - mysql
    build: 
      context: ./rest-api-app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DATABASE_HOST=mysql
    depends_on:
      - mysql
  web:
    build: 
      context: ./frontend-app
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
      